### ISSUE TITLE
md5sum: should there be a md5sum file?

### ISSUE THREAD

**Issue by pete4abw** [jrizzoli/vendor_google#14]
getmd5 function does not write md5sum file for zip. Isn't an md5sum useful for installation on devices?

function getmd5(){
    if [ -x $(which md5sum) ]; then
        echo "md5sum is installed, getting md5..." >> $GLOG
        echo "Getting md5sum..."
        GMD5=$(md5sum $OUT/$GARCH/$BUILDZIP)
        return 0
    else
        echo "md5sum is not installed, aborting" >> $GLOG
        return 1
    fi
}

**Comment by jrizzoli** [comment]
when you sideload a zip the device doesn't check its md5, even if there's the file.zip.md5 file. I just print it so i can copy-paste it on the readme.md of builds branch

**Comment by pete4abw** [comment]
Sideload, correct. Install using TWRP or similar always checks md5sum.
