### ISSUE TITLE
Minor code cleanup: for review

### ISSUE THREAD

**Issue by pete4abw** [jrizzoli/vendor_google#15]
Just some cleanup of unnecessary duplicate error code. exit 0 only occurs one place. Everything else is an error.

diff --git a/build/gapps.sh b/build/gapps.sh
index b800cf2..2528f68 100644
--- a/build/gapps.sh
+++ b/build/gapps.sh
@@ -100,15 +100,8 @@ if [ "$LASTRETURN" == 0 ]; then
             printdone "Build completed: $OUT/$GARCH/$BUILDZIP"
             printdone "            md5: $GMD5"
             exit 0
-        else
-            printerr "Build failed, check $GLOG"
-            exit 1
       fi
-    else
-        printerr "Build failed, check $GLOG"
-        exit 1
   fi
  -else
-    printerr "Build failed, check $GLOG"
-    exit 1
  fi
  +printerr "Build failed, check $GLOG"
  +exit 1

**Comment by jrizzoli** [comment]
Partially merged in 15.08
