### ISSUE TITLE
com.google.android.googlequicksearchbox crash

### ISSUE THREAD

**Issue by PerLycke** [jrizzoli/vendor_google#16]
com.google.android.googlequicksearchbox crashes due to it looking for libgoogle_recognizer_jni.so and can't find it. Copying libgoogle_recognizer_jni_l.so and naming it ibgoogle_recognizer_jni.so fixes it temporarily.

https://gist.github.com/PerLycke/a9e45a5d53d924a66e14

**Comment by gadkrumholz** [comment]
Thanks! This fixed it for me as well.

**Comment by jrizzoli** [comment]
Fixed in 15.08
