### ISSUE TITLE
updater-script

### ISSUE THREAD

**Issue by cyboerg42** [jrizzoli/vendor_google#17]
In the newest build of gapps for arm (gapps-5.1-2015-07-03-13-41.zip), i've discover'd this issue :

run_program("/systen/gapps_scripts.sh", ""); - Should be : run_program("/system/gapps_scripts.sh", "");

**Comment by stucki** [comment]
Just noticed the same, see #18

**Comment by jrizzoli** [comment]
Fixed in 15.08
