### ISSUE TITLE
How are the files obtained?

### ISSUE THREAD

**Issue by Lekensteyn** [jrizzoli/vendor_google#2]
Where are the binary files obtained from? Is it "another random zip" retrieved from XDA?

Failing to find an auditable track for the files last week, I started documenting the required files at https://github.com/Lekensteyn/make-gapps-zip (which might help you as well).

**Comment by Lekensteyn** [comment]
Not even a comment on this question? Wow. You must already have backdoored all files.

**Comment by cgapps** [comment]
It has been closed because there's no reason to reply to a "spam" (your github repo). Also the only question u asked has an answer on the README.md (that u did not read)

**Comment by Lekensteyn** [comment]
The README (which I did read) only mentions the factory images, but that is not specific enough. The 5.1.0 (LMY47I) factory image for the Nexus 5 contains odex files for ART which is currently not fully supported by smali (https://github.com/JesusFreke/smali/pull/30). Your APK files have no such odex files, hence the question about the source.

The contents of the LM47I image are documented in my repo because there was no better place to put it.

Now, can you clarify where the files are really retrieved from? The goal is to have a reproducible path from the factory images to the apk files (such as the ones locates in your repository).

**Comment by Lekensteyn** [comment]
@cgapps (a.k.a. @linuxxxxx?)
How did you produce these files?
