### ISSUE TITLE
your links on cm wiki lead to broken zips. fyi

### ISSUE THREAD

**Issue by razorloves** [jrizzoli/vendor_google#20]
The zips have the wrong directory structure and just fail to flash. Everything that should be in the root of the zip is actually in a folder.

**Comment by swapsCAPS** [comment]
Yup, I second this. Just extract and rezip and it'll work just fine though.

**Comment by MasterCylinder** [comment]
However, the md5 file inside is titled: gapps-5.1-arm-2015-07-09-15-16.md5, relating to a zip which doesn't exist and which doesn't jibe with the build date which is 7/03? And, I can't get this md5 file to match up to anything. I can get it to flash fine after rebuilding it but this hash doesn't fit anywhere.

**Comment by razorloves** [comment]
fixed

**Comment by swapsCAPS** [comment]
Hahaha Github doesn't suck! :p It's just not really meant to serve flashable zips for n00bs

**Comment by jrizzoli** [comment]
@stofstik then it does :P

**Comment by MasterCylinder** [comment]
@jrizzoli Thanks for your builds! Gotta link in the OP of a cm thread on xda.
