### ISSUE TITLE
path in md5 file should be relative

### ISSUE THREAD

**Issue by chaoflow** [jrizzoli/vendor_google#21]
https://github.com/cgapps/vendor_google/blob/builds/arm/gapps-5.1-arm-2015-07-17-13-29.md5

**Comment by chaoflow** [comment]
The md5 file references a file for July 11th. Changin the 11 to 17 and removing its path, the md5 sum is correct for the zip file next to it.

**Comment by jrizzoli** [comment]
i accidetally edited the date on the md5. Mea culpa
