### ISSUE TITLE
Excluding not strictly necessary apps

### ISSUE THREAD

**Issue by ghost** [jrizzoli/vendor_google#3]
Can you add a way to exclude apps that are not strictly necessary?
- FaceLock
- GoogleCalendarSyncAdapter
- GoogleContactsSyncAdapter
- Velvet (Google Search)

Or should we just manually delete the folders from `app` / `priv-app`?

**Comment by cgapps** [comment]
Nope, these are needed to get a working google account

**Comment by cgapps** [comment]
Facelock is removed if the device does not support it

**Comment by ghost** [comment]
> Nope, these are needed to get a working google account

They're definitely not needed, my Nexus 5 runs **just fine** without them. I don't know why every gapps packager insists on saying the sync adapters are essential. They aren't.

> Facelock is removed if the device does not support it

That's completely irrelevant. My device does support it, but I find it useless.

---

Let me make something clear. Including these apps makes complete sense, because they (and the other included apps) are the only ones you can't just get from the Play Store (with the exception of Google Search, which just needs system permissions for some things, like "OK Google").

But not everyone needs them.

**Comment by ghost** [comment]
Or are you saying the setup wizard doesn't work if the sync adapters are missing? I'm not sure whether I tested that.

**Comment by cgapps** [comment]
sync adapter are needed to sync stuffs from google server
