### ISSUE TITLE
Force Close with TrustedFace (SmartLock)

### ISSUE THREAD

**Issue by neo4matrix** [jrizzoli/vendor_google#6]
E/AndroidRuntime( 8921): FATAL EXCEPTION: main

E/AndroidRuntime( 8921): Process: com.android.facelock, PID: 8921

E/AndroidRuntime( 8921): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/FaceLock/FaceLock.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libfacelock_jni.so"

E/AndroidRuntime( 8921):    at java.lang.Runtime.loadLibrary(Runtime.java:366)

E/AndroidRuntime( 8921):    at java.lang.System.loadLibrary(System.java:988)

E/AndroidRuntime( 8921):    at com.android.facelock.FaceLockUtil.<clinit>(FaceLockUtil.java:338)

E/AndroidRuntime( 8921):    at com.android.facelock.SetupFaceLock$SetupFaceLockFragment.onCreateView(SetupFaceLock.java:302)

E/AndroidRuntime( 8921):    at android.app.Fragment.performCreateView(Fragment.java:2053)

E/AndroidRuntime( 8921):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)

E/AndroidRuntime( 8921):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)

E/AndroidRuntime( 8921):    at android.app.BackStackRecord.run(BackStackRecord.java:834)

E/AndroidRuntime( 8921):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)

E/AndroidRuntime( 8921):    at android.app.Activity.performStart(Activity.java:6005)

E/AndroidRuntime( 8921):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2319)

E/AndroidRuntime( 8921):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)

E/AndroidRuntime( 8921):    at android.app.ActivityThread.access$900(ActivityThread.java:154)

E/AndroidRuntime( 8921):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)

E/AndroidRuntime( 8921):    at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 8921):    at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 8921):    at android.app.ActivityThread.main(ActivityThread.java:5293)

E/AndroidRuntime( 8921):    at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 8921):    at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 8921):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)

E/AndroidRuntime( 8921):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

W/ActivityManager(  748):   Force finishing activity 1 com.android.facelock/.SetupFaceLock

**Comment by jrizzoli** [comment]
the issue has already been fixed

**Comment by hexchain** [comment]
I'm still having this issue, particularly after a CM dirty flash update. In M1 release zip there's no `system/app/FaceLock/lib/libfacelock_jni.so`(which should be a link to actual file) , only `system/lib/libfacelock_jni.so`, but the latter is not listed in `addon.d/31-faceunlock.sh`, resulting the file not being backed up upon flashing.
